### ISSUE TITLE
Cannot install 0.4.3

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#84]
Fails on `guild init`

```
Collecting ml-workflow==0.4.3
  Downloading ml-workflow-0.4.3.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/richard/Documents/test-coop/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a5y7bcfb/ml-workflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a5y7bcfb/ml-workflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a5y7bcfb/ml-workflow/pip-egg-info
         cwd: /tmp/pip-install-a5y7bcfb/ml-workflow/
    Complete output (24 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/packaging.py", line 858, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "/tmp/pip-install-a5y7bcfb/ml-workflow/.eggs/pbr-5.4.4-py3.6.egg/pbr/packaging.py", line 826, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "/usr/lib/python3.6/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.6/email/parser.py", line 54, in parse
        data = fp.read(8192)
      File "/home/richard/Documents/test-coop/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 157: ordinal not in range(128)
    error in setup command: Error parsing /tmp/pip-install-a5y7bcfb/ml-workflow/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 157: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by Jim-Holmstroem** [comment]
so we have Swedish letters under authors, fixing this

**Comment by Jim-Holmstroem** [comment]
hopefully fixed through https://github.com/codewell/ml-workflow/commit/f8b183ebe5115aecec6c9c8cb79389a75fd2155d

this wasn't an issue for me so I don't think we need to yank the current 0.4.3, just publish a new one

the only other place there is weird letters that I could find was under AUTHORS which is generated from git log

**Comment by Jim-Holmstroem** [comment]
managed to reproduce in `python-3.6`
(does not appear in `python-3.8`)

**Comment by Jim-Holmstroem** [comment]
could potentially be a difference between using a guild installed python or the host python as well (haven't looked closer into this)

**Comment by Jim-Holmstroem** [comment]
```
FROM python:3.6

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir guildai==0.7.0rc7

COPY . .

RUN guild init --yes

```

reproduces it

**Comment by Jim-Holmstroem** [comment]
Verified to be fixed by https://github.com/codewell/ml-workflow/commit/f8b183ebe5115aecec6c9c8cb79389a75fd2155d
